#learning rate is typically between 0.1 and 0.4
learningRate: 0.1
#number of iterations to allow the perceptron to train for
maxIterations: 100
#training percentage is typically between 0.5 and 0.6
trainingPercentage: 0.6
#cross-validation folds should be less than the number of inputs
folds: 5
inputFile: 'supervised3by3.csv'